# Generated by Django 2.2.4 on 2024-07-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date_updated',
            new_name='date_added',
        ),
    ]
