# Generated by Django 2.2.4 on 2024-07-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_auto_20240719_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
