# Generated by Django 2.2.4 on 2024-07-19 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course_app.Description'),
        ),
    ]
