# Generated by Django 2.2.4 on 2024-07-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Ninja',
        ),
    ]
