# Generated by Django 2.2.4 on 2024-07-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
    ]
