# Generated by Django 2.2.4 on 2024-07-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=0.0018351214003387917, max_length=100),
            preserve_default=False,
        ),
    ]
