# Generated by Django 2.2.4 on 2024-07-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filling', models.CharField(max_length=50)),
                ('crust', models.CharField(max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakers', to='my_app.User')),
            ],
        ),
    ]
