# Generated by Django 2.2.4 on 2024-07-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_show',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
